README.md
Not sure If it is a requirement for mac, but for me running:
`PROXY=true npm run start:beta`
resulted in: 
```
npm ERR! missing script: start:beta
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     start
```
@amirfefer  Maybe we should add it as a different option?
=> Fix instructions to run npm run start command

package-lock.json, package.json, src/Components/Common/GlobalState/index.js, src/Components/Common/GlobalState/initialState.js, src/Components/SourcesDropdown/index.js, src/mocks/utils.js
_Depends on #13 and #16 as different commits_ 
This PR adds a simple global state with (react-tracked)[https://react-tracked.js.org]
React Context API has some drawbacks,  it's not performance-wise out of the box, and it might re-render all of the components that consume it and trigger performance issues, this [thread](https://www.basefactor.com/global-state-with-react) explains these drawbacks.
Yes and no, react-query has a different approach than the classic redux/store, it represents the server state, while this global state represents some global client's variables that need to be reused by other components.
For example, let's take the `<SourcesDropdown>` -  it represents all the provisioning sources that the user can choose from. `react-query` is responsible for fetching, mutating, …
=> Add simple global state

src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js, src/mocks/fixtures/instanceTypes.fixtures.js
While the tests are running there are some console errors:
1. 
```    console.error
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `InstanceTypesSelect`. See https://reactjs.org/link/warning-keys for more information.
````
reason: the fixtures don't have `id` props
2.
```
Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one.
```  
reason: `waitFor`  is async and should be wrapped by a promise / async-await
=> Fix console errors during tests

README.md, config/jest.setup.js, docs/dev.md, docs/testing.md, src/Components/Common/GlobalState/__mocks__/initialState.js, src/Components/Common/GlobalState/index.js, src/Components/Common/WizardContext/__mocks__/initialState.js, src/Components/Common/WizardContext/index.js, src/Components/Common/WizardContext/initialState.js, src/Components/DescriptionListAWS/index.js, src/Components/InstanceCounter/index.js, src/Components/InstanceTypesSelect/index.js, src/Components/SourcesSelect/index.js, src/Components/Wizard/index.js, src/mocks/utils.js
`GlobalState` can be a confusing term, `WizardContext` describes better the domain
=> rename globalState to wizardContext

src/Components/DescriptionListAWS/index.js, src/Components/ExpandableAWS/index.js, src/Components/Wizard/index.js, src/Components/Wizard/steps/ReviewDetails/index.js, src/Components/Wizard/steps/index.js, src/Routes/SamplePage/SamplePage.js
This adds an `image` prop to the `ProvisioningWizard` component
This prop is an object with a shape of `{ name: string, ami: string }`
The [ami](https://github.com/RedHatInsights/image-builder-frontend/blob/main/src/Components/ImagesTable/ImageLink.js#L29) already exists in the image-builder front application, so it seems redundant to fetch it later in our backend by the image identifier. The image's name prop propagates to the review page, so the user is notified just before the reservation is made.
```js
<ProvisioningWizard
isOpen={isWizardOpen}
onClose={onCloseFn}
image={{ name: 'example-image', ami: 'ami-0c830793775595d4b' }}
/>
```
=> Add image prop to wizard

deploy/frontend.yaml
As per other teams examples, this needs to be an app name, not component name.
Thanks @karelhala :)
FYI @mshriver, @jlsherrill
=> Correct name in clowder template metadata

src/Routes/SamplePage/SamplePage.js
Just a simple addition of input for manually entering an AMI that we want to provision.
This should be just a fallback, when IB is not available, but will be useful until IB is in ehpemeral environment and also for easier local testing.
=> Allow entering AMI manually from sample page

src/API/index.js, src/Components/Wizard/index.js, src/Components/Wizard/steps/FinishProgress/index.js, src/Components/Wizard/steps/FinishProgress/styles.scss, src/Components/Wizard/steps/index.js
Depended on #56
https://user-images.githubusercontent.com/11807069/186199592-29d07436-d04c-4084-9866-0b2ba732c25b.mov
https://user-images.githubusercontent.com/11807069/186199645-e02cfb48-8400-428e-8c4b-a2c4cebb5ef8.mov
This PR adds a progress screen after submission, developed according to  PF4 design recommendation: https://www.patternfly.org/v4/components/wizard/design-guidelines
=> Add finish progress step

src/Components/DescriptionListAWS/index.js, src/Components/RegionsSelect/index.js, src/Components/Wizard/steps/FinishProgress/index.js
This is a temporary fix!
- Removing the hard-coded "US- east" 
- Using the default value we have in the wizardContext. 
After getting all the information we need about regions from image builder we would list only the regions the customer had chosen in image builder step.
=> Add region to createAWSDeployment

src/Components/ConfirmModal/index.js, src/Components/ProvisioningWizard/index.js, src/Components/ProvisioningWizard/steps/ReviewDetails/index.js, src/Components/ProvisioningWizard/steps/index.js
Unify finish button text and use "Launch" label
Add exit confirmation, when user has reached the review step and thus 
filled a lot of data (previous steps will still allow canceling without confirm).
=> Review step ux

src/API/index.js, src/API/queryKeys.js, src/Components/InstanceTypesSelect/index.js, src/mocks/handlers.js
Uses the new static endpoint to load instance types.
Depends on https://github.com/RHEnVision/provisioning-backend/pull/245
=> Swith to new instance types endpoint

src/Components/ProvisioningWizard/steps/Pubkeys/NewKeyForm.js
Parent component refresh makes cursor to move.
We need to keep the state in the local component
Fixes HMSPROV-270
=> fix(pubkeys): Component refresh does not move cursor

.gitignore, config/routes.config.js, fec.config.js, package.json
This PR extracts the local routes (i.e local API server) from the `fec.config` and allows running frontend with no local provisioning API (communicates directly to the stage)
``` bash
npm run start:stage 
```
```bash
npm run start
```
=> enable running front dev with staged api backend

docs/testing.md, src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js, src/Components/ProvisioningWizard/steps/Pubkeys/Pubkeys.test.js, src/Components/SourcesSelect/SourcesSelect.test.js
`userEvent` is made for mimicking  real user interactions with the screen, react testing library recommends using it  for testing user interactions (i.e typing, clicking, mouse focus)  over the lower api `fireEvent`
=> fix(HMSPROV-378) - use userEvent over fireEvent

src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js, src/Components/InstanceTypesSelect/index.js
This PR allows filtering instance's types with any substring within the type, i.e -  for searching  `micro`, I'll get all the micro types.
=> fix(HMSPROV-406): filter instance types with substring

src/Components/Common/Hooks/useInterval.js, src/Components/ProvisioningWizard/steps/FinishProgress/FinishProgress.test.js, src/Components/ProvisioningWizard/steps/FinishProgress/constants.js, src/Components/ProvisioningWizard/steps/FinishProgress/index.js, src/mocks/fixtures/reservation.fixtures.js, src/mocks/handlers.js
This demonstrates another implementation for a timeout session with no use of additional timers. 
In addition, this PR reduces the number of round trips to the server, due to an interval that increased (not linear) for each try.
=> feat(HMSPROV-419): add a timeout session for reservation polling 

src/App.js
chrome.init has been deperecated in new release of frontend-utilities
Fixes HMSPROV-430
=> fix: move to useChrome hook

src/Components/ProvisioningWizard/steps/Pubkeys/NewKeyForm.js, src/Components/ProvisioningWizard/steps/Pubkeys/Pubkeys.test.js, src/Components/ProvisioningWizard/steps/Pubkeys/index.js
This fixes the ssh authentication page after a failure and  editing the form.
=> fix(HMS-1195): fix ssh page after edit

src/Components/ProvisioningWizard/CustomFooter.js, src/Components/ProvisioningWizard/index.js, src/Components/ProvisioningWizard/steps/ReservationProgress/index.js, src/Components/ProvisioningWizard/steps/index.js
Add custom ids to Provisioning wizard.
The buttons needed a CustomHeader for the id to be set.
Fixes HMS-1127
=> refactor: Add custom ids to wizard buttons

src/Components/SourcesSelect/index.js
the `provider` is undefined at first rendering,  causes an extra triggering of `/sources?provider=undefiend` which ended up with 404
=> fix(HMS-1361): fix a 404 api call at first rendering

src/Components/ProvisioningWizard/steps/ReservationProgress/ExpansionInfo.js
Instead of picking `reservation_id`(hidden) in the iqe test, add ouid and looking for the Card in show additional info launch_id makes more sense in the test
=> Add ouid for Card on show additional info

src/Components/Common/constants.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/index.js, src/Components/ProvisioningWizard/steps/index.js, src/Components/SourcesSelect/SourcesSelect.test.js, src/Components/SourcesSelect/index.js
This PR matches Image builder change to share images with a source rather than an account ID (AWS for now). 
Image builder have added a prop name: sourceId on their side. (currently, image builder UI supports only sharing with one source and the provisioning service as well)
In this PR we are preselecting the source to the one given by IB, and showing it as disabled (You cannot change the source from the dropdown). 
This addition currently is only for AWS, in GCP and Azure the source should be selected from the dropdown. 
_Good To Know:_ 
After the change IB did it is **not possible** to use sources locally, you should use sources stage, make sure you have added a source there. 
If the image was not shared with a source the Launch button is not going to appear. (in AWS we do not allow …
=> Add support to a source shared with an image

src/API/index.js, src/API/queryKeys.js, src/Components/LaunchDescriptionList/index.js, src/Components/ProvisioningWizard/helpers.js, src/Components/ProvisioningWizard/index.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/index.js, src/Components/ProvisioningWizard/steps/SourceMissing/DirectProviderLink.js, src/Components/ProvisioningWizard/steps/SourceMissing/SourceMissing.test.js, src/Components/ProvisioningWizard/steps/SourceMissing/index.js, src/Components/ProvisioningWizard/steps/index.js, src/Components/RegionsSelect/index.js, src/Components/SourcesSelect/index.js, src/Routes/SamplePage/SamplePage.js
Adds empty state when no Source that can Launch given image is found. Provides link to Source creation.
Makes sure to refetch the empty state regularly so users do not need to refresh page. Adds fallback link for users who want to launch through cloud providers console directly.
Refs HMS-1583
NEW only empty state update - with region: 
[Screencast from 2023-04-13 14-02-44.webm](https://user-images.githubusercontent.com/2884324/231752847-2c5abab5-3ed3-43c7-a022-69d9ce0b62fb.webm)
~~Old: [Screencast from 2023-04-07 01-08-48.webm](https://user-images.githubusercontent.com/2884324/230512943-f3717717-9c06-4545-b08c-2975f60a4fee.webm)~~
=> feat: add empty state when no source available

src/Components/ProvisioningWizard/helpers.js
Refs HMS-1409
The source information is stored differently for Azure then for AWS.
=> feat: support for Azure image deployed to source account

src/API/queryKeys.js, src/Components/Common/Hooks/sources.js, src/Components/Common/WizardContext/__mocks__/initialState.js, src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js, src/Components/LaunchDescriptionList/index.js, src/Components/ProvisioningWizard/helpers.js, src/Components/ProvisioningWizard/index.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/azure.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/gcp.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/index.js, src/Components/ProvisioningWizard/steps/SourceMissing/DirectProviderLink.js, src/Components/ProvisioningWizard/steps/SourceMissing/SourceMissing.test.js, src/Components/ProvisioningWizard/steps/index.js, src/Components/SourcesSelect/SourcesSelect.test.js, src/Components/SourcesSelect/index.js, src/Components/TemplateSelect/TemplateSelect.test.js, src/constants.js, src/mocks/fixtures/image.fixtures.js, src/mocks/fixtures/sources.fixtures.js, src/mocks/handlers.js, src/mocks/utils.js
This improves how we fetch usable sources.
Uses the filtered sources for the Sources select.
Drops notion of Shared with source in the select.
Insted preselects the source when only single is available to use.
Fixes HMS-1625
This goes above what we have implemented in #238 and uses the same approach for the sources select.
IMO much supperior approach as Users can select only sources that are usable to launch the given image.
IMO this is a great UX improvemet :)
On top of implemented changes, I've changed tests, so test itself is able to set the context values directly.
=> feat: filter source in the select

src/Components/ProvisioningWizard/index.js
PF4 wizard currently doesn't delegate the `appendTo` property so that it can be anchored to proper element. This removes the `isOpen` property so as not to force modal window. Callers of the Wizard need to wrap it in their own modal.
PF4 issue: https://github.com/patternfly/patternfly-react/issues/8972
=> Remove `isOpen` from Wizard

src/Components/Common/Hooks/sources.js, src/Components/ProvisioningWizard/ProvisioningWizard.test.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/azure.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/gcp.js, src/Components/ProvisioningWizard/steps/index.js, src/mocks/fixtures/sources.fixtures.js, src/mocks/utils.js
Mainly simplifies the step decision, so we dont flip rendered wizard steps there and back.
Adds tests for the form itself, for now only tests the loading and empty state. Fixes import of the icons.
Fixes HMS-1657
=> fix: sources loading when one source failing

src/Components/ProvisioningWizard/steps/SourceMissing/SourceMissing.test.js, src/Components/ProvisioningWizard/steps/SourceMissing/index.js
Currently we are only in preview, but we want to respect the toggle.
I'm keeping the change as simple as possible, in the future, we will want to do this dynamically.
Fixes HMS-1757
=> fix: Sources link respect preview toggle

src/Components/RegionsSelect/RegionsSelect.test.js, src/Components/RegionsSelect/index.js
If an AWS in image-builder has been cloned to one other region, then the region select dropdown is disabled in theprovisioning wizard, and the user can't select the 2nd region. This is only an issue when the image has been cloned only once; if the image is shared to a third region, then the dropdown is enabled.
This PR fixes that issue so that the dropdown is always enabled.
=> Fix region select disabled in AWS provisioning wizard

src/API/index.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js, src/mocks/handlers.js
Launch templates seems to be a poplular feature and we've decided to support it. The flag is no longer needed.
Fixes HMS-1850
=> feat: remove feature flag for AWS launch template

src/Components/Common/Query/index.js, src/Components/InstanceTypesSelect/index.js, src/Components/ProvisioningWizard/steps/ReservationProgress/index.js
Requests from client side are triggered multiple times due to missing configuration in react-query , data becomes stale as soon as it fetched, for further configuarion defaults of react-query - https://tanstack.com/query/v4/docs/react/guides/important-defaults 
This PR adds a global `staleTime` of 10 seconds, which is still aggresive policy,  but cancel it during resevation polling.
I recored the amount of requests during  wizard steps progress before polling:
before:
https://user-images.githubusercontent.com/11807069/236284179-6f4f56ed-66f9-4908-87f3-ffbda47e7d5e.mov
after:
https://user-images.githubusercontent.com/11807069/236284230-7aa9f1cd-35bb-44af-9af4-3928140538dd.mov
More about `staleTime`, this [post](https://www.codemzy.com/blog/react-query-cachetime-staletime) covers it well
=> fix(HMS-1748): use staleTime config for preventing multiple requests

src/Components/Common/Hooks/sources.js, src/Components/InstancesTable/helpers.js, src/Components/ProvisioningWizard/steps/SourceMissing/DirectProviderLink.js, src/Components/SourcesSelect/SourcesSelect.test.js, src/mocks/fixtures/sources.fixtures.js, src/mocks/handlers.js
Depends on https://github.com/RHEnVision/provisioning-backend/pull/571
- A function for filtering GCP sources was missing so I added it.
- a general link for GCP was added as well, it needs to be refactored to direct the customer to his specific project, I opened a bug for it. 
- Instances table will be added next
For now, we are relying on getting from the backend the email that the image was shared with.
=> fix(HMS-1917): Add source filtering for GCP

src/Components/ProvisioningWizard/steps/ReservationProgress/index.js
In some cases, a polled reservation might be set at its final step (i.e. step 3 out of 3), but the `success` flag is still null, this caused the frontend app to end up polling.
polled reservation:
```
{
"id": 25,
"provider": 2,
"created_at": "2023-06-25T18:33:20.686045Z",
"steps": 3,
"step_titles": [
"Ensure public key",
"Launch instance(s)",
"Fetch instance(s) description"
],
"step": 3,
"status": "Instance(s) description fetched",
"error": "",
"finished_at": null,
"success": null
}
```
=> fix(HMSPROV-2012): fix missing instances table

src/Components/Common/instanceHelpers.js, src/Components/InstancesTable/helpers.js, src/Components/ProvisioningWizard/steps/ReservationProgress/ReservationProgress.test.js, src/Components/ProvisioningWizard/steps/ReservationProgress/constants.js, src/Components/ProvisioningWizard/steps/SourceMissing/SourceMissing.test.js, src/mocks/fixtures/reservation.fixtures.js, src/mocks/handlers.js
This PR adds an instance description table at the end of a successful launch and also adds missing tests.
=> feat(HMS-1879): Add instance desc table for GCP

src/Components/InstancesTable/index.js, src/Components/ProvisioningWizard/steps/ReservationProgress/ReservationProgress.test.js
for GCP and Azure public DNS are not defined, this PR exposes the DNS column only if at least one launched instance has a public DNS defined.
=> feat(HMS-2022): Show DNS column only if public_dns(s) are not empty

src/Components/GCPConsoleLaunch/GCPConsoleLaunch.scss, src/Components/GCPConsoleLaunch/index.js, src/Components/ProvisioningWizard/steps/SourceMissing/DirectProviderLink.js, src/Components/ProvisioningWizard/steps/SourceMissing/SourceMissing.test.js, src/Components/ProvisioningWizard/steps/SourceMissing/index.js
This PR adds launch instance command clipboard to GCP Empty state when there aren't any GCP sources available
=> feat(HMS-1930): Add image command clipboard for GCP

.rhcicd/pr_check.sh
This should run frontend pr_check for aws and gcp. Azure image is not in the env because of the plaintext compose request will contain secrets.
=> ci: (HMS-2129) Update frontend test markers (workaround)

src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js, src/Components/InstanceTypesSelect/index.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/azure.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/gcp.js, src/Components/RegionsSelect/index.js, src/Components/SourcesSelect/index.js, src/Components/TemplateSelect/index.js, src/mocks/fixtures/instanceTypes.fixtures.js
This PR enhances the Account and customization step in the wizard
- All select inputs have `maxHeight` for fixing select content override
- Content is aligned to the wizard layout, minimizes the need for a scroll bar
- Alert warning for the instance types is removed and replaced by inner validation and helper text
- Instance type select switched location with Templates select
- Template select's dropdown opens in the upper direction
Before:
https://github.com/RHEnVision/provisioning-frontend/assets/11807069/1a5e027e-286b-4d31-83f0-518b805b719c
After:
https://github.com/RHEnVision/provisioning-frontend/assets/11807069/034ff612-668d-4744-b395-29089511c092
=> fix(HMS-2256): enhance wizard first page interface

src/Components/ProvisioningWizard/steps/Pubkeys/PubkeySelect.js
When an invalid format for Azure key is selected, and then a valid (RSA) key is selected, the validation is not cleared, so it still seems like the key is not valid.
=> fix(HMS-2297): clear key format error

src/API/index.js, src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js, src/Components/ProvisioningWizard/steps/Pubkeys/Pubkeys.test.js, src/Components/SourcesSelect/SourcesSelect.test.js, src/Components/TemplateSelect/TemplateSelect.test.js, src/mocks/fixtures/instanceTypes.fixtures.js, src/mocks/fixtures/pubkeys.fixtures.js, src/mocks/fixtures/sources.fixtures.js, src/mocks/fixtures/templates.fixtures.js
Tested with
https://github.com/RHEnVision/provisioning-backend/pull/638 and https://github.com/RedHatInsights/image-builder-frontend/pull/1299
Verified with a successful  aws launch
=> feat(HMS-2304): Nest list endpoints with 'data'

package.json
Part of the frontend containerization, jest needs to run with no-cache
=> build: disable jest cache

src/Components/TemplateSelect/index.js
This PR continues the refactoring for removing alerts into inline validations:
=> feat(HMS-2378): refactor the template select alert

src/Components/ProvisioningWizard/steps/ReservationProgress/index.js
When the reservation polling fails after a few attempts,  (status != 200), the reservation was created already successfully, but there is no way to fetch the current launch status, this PR adds a warning , something like:
=> fix(HMS-2261): show warning when polling reservation fails

src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/gcp.js
This PR Adds the word "Optional" to select templates field to better indicate that it is optional.
Another solution is to use patternfly Form's `additionalLabel` prop:
/cc @MariSvirik
=> fix(HMS-1913): add an optinal string to template select

config/jest.setup.js, package-lock.json, package.json, src/API/queryKeys.js, src/Components/Common/Hooks/sources.js, src/Components/Common/Query/index.js, src/Components/InstanceCounter/index.js, src/Components/InstanceTypesSelect/index.js, src/Components/InstancesTable/index.js, src/Components/LaunchDescriptionList/index.js, src/Components/ProvisioningWizard/ProvisioningWizard.test.js, src/Components/ProvisioningWizard/steps/Pubkeys/PubkeySelect.js, src/Components/ProvisioningWizard/steps/Pubkeys/Pubkeys.test.js, src/Components/ProvisioningWizard/steps/Pubkeys/index.js, src/Components/ProvisioningWizard/steps/ReservationProgress/index.js, src/Components/RegionsSelect/index.js, src/Components/TemplateSelect/index.js, src/mocks/utils.js
This PR migrate to react-query v4, following the formal migration [guide](https://tanstack.com/query/v4/docs/react/guides/migrating-to-react-query-4)
=> feat(HMS-2444): migrate to react-query v4

babel.config.js, fec.config.js, jest.config.js, package-lock.json, package.json, src/Components/ProvisioningWizard/ProvisioningWizard.test.js, src/Components/ProvisioningWizard/steps/index.js
When building this react app, webpack throws a warning regarding bundle size, as you can see in the following screenshot, 2 chunks exceed the limit of 250 KB:
These two files are related to patternfly-core and patternfly-table. By using treeshaking via babel-transform and code spiting, the bundle is reduced by 50%
In addition, this PR adds `analyze` to package.json scripts, in order to build and see a full report.
The main gist of the PR is based on the patterfly-core treeshaking is documented [here](https://github.com/RedHatInsights/frontend-components#treeshaking-pf-with-babel-plugin)
=> fix(HMS-2428): reduce the bundle size by 50%

.github/workflows/provisioning-front.yml, .github/workflows/sync_branches.yml
Part of the containerized frontend process.
=> feat(HMS-2369): remove stage old deployment

.github/workflows/provisioning-front.yml
in GitHub action, we use yarn for building, but we use npm.
=> build: use npm build instead of yarn

src/Components/InstancesTable/helpers.js, src/Components/InstancesTable/index.js
This adds an export to csv button to the instances table
vs
=> feat(HMS-1897): add export to csv btn to instances table

src/Components/ProvisioningWizard/ProvisioningWizard.test.js, src/Components/ProvisioningWizard/index.js, src/Components/ProvisioningWizard/steps/NoPermission/index.js
Depends on https://github.com/RedHatInsights/image-builder-frontend/pull/1343
=> feat(HMS-2496): add no permission empty state

src/Components/ProvisioningWizard/steps/SourceMissing/DirectProviderLink.js, src/Components/RegionsSelect/index.js
Moves the error state on RegionSelect to use inline FormHelperText and error validations.
The fix itself is wrapping the RegionSelect in FormGroup.
BEFORE:
AFTER:
=> fix(HMS-2618): format regions error correctly

src/Components/ProvisioningWizard/steps/SourceMissing/DirectProviderLink.js, src/Components/ProvisioningWizard/steps/SourceMissing/GCPConsoleLaunch.js, src/Components/ProvisioningWizard/steps/SourceMissing/GCPConsoleLaunch.scss, src/Components/ProvisioningWizard/steps/SourceMissing/SourceMissing.scss, src/Components/ProvisioningWizard/steps/SourceMissing/index.js, src/Components/RegionsSelect/index.js
Unifies the delimiter of DirectProviderLink.
Moves delimiter out of the DirectProviderLink for other usage (No Permissions).
GCP:
AWS:
@adiabramovitch any reason we had the OR delimiter just for GCP?
=> fix(HMS-2034): Unify missing source empty state

src/API/index.js, src/API/queryKeys.js, src/Components/AzureResourceGroup/AzureResourceGroup.test.js, src/Components/AzureResourceGroup/index.js, src/Components/LaunchDescriptionList/index.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/azure.js, src/Components/ProvisioningWizard/steps/ReservationProgress/index.js, src/mocks/fixtures/sources.fixtures.js, src/mocks/handlers.js, src/mocks/utils.js
[Screencast from 2023-10-05 20-27-33.webm](https://github.com/RHEnVision/provisioning-frontend/assets/2884324/7531a879-93a0-48c4-aec0-9427479d23f8)
Simple and straightforward I hope :)
UI part for https://github.com/RHEnVision/provisioning-backend/pull/694
Update your backend env or test with stage! :)
=> feat(HMS-1772): Allow selecting custom resource group

src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js, src/Components/InstanceTypesSelect/index.js
Previously:
The InstanceTypesSelect would only show results for an architecture if the architecture returned by the backend was exactly matching the one asked by the user.
This proved to be problematic because some architecures can have many names. For instance `aarch64` can be interchangeably used with `arm64`.
To to make the ProvisionningWizard more flexible, the instance selection dropdown now is using the same name mapping for the architectures as the one found in the backend. See:
https://github.com/RHEnVision/provisioning-backend/blob/0f3abc7328ebda3314d7496544b019a36a061152/internal/clients/architecture.go#L25
This work is related to HMS-1135
=> InstanceTypesSelect: improve arch compatibility

src/Components/ProvisioningWizard/steps/ReviewDetails/index.js
I've also reworded it to be more "call to action" title, given now less people will see the body.
=> docs: make notification tip expandable to take less space

src/Components/AzureResourceGroup/AzureResourceGroup.test.js, src/Components/AzureResourceGroup/index.js, src/Components/LaunchDescriptionList/index.js, src/Components/ProvisioningWizard/helpers.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/azure.js, src/Components/ProvisioningWizard/steps/ReviewDetails/index.js, src/Components/ProvisioningWizard/steps/index.js
Use image RG by default and display clearly what the default is.
This also removes the region selection entirely, as we default to the Resource Group location(region) and that's the best practice in Azure, so we don't want to promote overriding it.
We have went to allowing Customers to shoot themselves in the foot a bit by selecting a wrong resource group, but we decided that's a better option, than disabling it completely, as we found customer value in customizing the RG.
Second version to #353 with enabling override for the resource group.
[Screencast from 2023-10-25 13-17-04.webm](https://github.com/RHEnVision/provisioning-frontend/assets/2884324/c4644daa-5d7c-46e4-9d69-9d1fdb1268ba)
=> feat(HMS-2255): deploy to image RG by default

src/Components/LaunchDescriptionList/index.js
Removes region info from Review for Azure.
For Azure we use Resource Group insted.
Refs HMS-2255
=> fix: do not show region in review for Azure provider

.github/workflows/provisioning-front.yml, .rhcicd/build_deploy.sh, .rhcicd/pr_check.sh, jest.config.js, jest.polyfills.js, package-lock.json, package.json, src/Components/AzureResourceGroup/AzureResourceGroup.test.js, src/Components/ProvisioningWizard/ProvisioningWizard.test.js, src/Components/ProvisioningWizard/steps/Pubkeys/Pubkeys.test.js, src/Components/ProvisioningWizard/steps/ReservationProgress/ReservationProgress.test.js, src/Components/RegionsSelect/RegionsSelect.test.js, src/Components/TemplateSelect/TemplateSelect.test.js, src/mocks/handlers.js, src/mocks/server.js, tsconfig.json
WIP
This PR update `msw` mocking server worker, which is used in our tests.
The msw (1.x -> 2.x) update is required for updating  `@redhat-cloud-services/frontend-components-config` due to typescript peer dependent.
=> fix(HMS-3373):  update msw and frontend-components-config

src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js
This PR adds unit test cases to verify the filtering functionality of the application. The test cases cover different scenarios, including filtering with queries greater than, less than, equal to, and combinations.
Local execution results :
```
npm test -- --testNamePattern="filter with a query greater than|filter with a query less than|filter with a query combination|filter with a query equal"
Test Suites: 11 skipped, 1 passed, 1 of 12 total
Tests:       53 skipped, 4 passed, 57 total
Snapshots:   0 total
Time:        36.834 s
Ran all test suites with tests matching "filter with a query greater than|filter with a query less than|filter with a query combination|filter with a query equal".
```
=> fix(HMS-3593): Added unit test cases for instance type selection

deploy/testing-integration.yaml
New sel image is failing the test pipeline because it does not have a controlled shutdown command, making the pod stuck and resulting into timeout.
=> ci: Reverting back to old sel image

.eslintrc.yml
We are using babel to transform the relative pf imports, we do not need to use relative lints explicitly.
Disabling the lint is needed in that case not to force us out of the relative lints.
The transformation happens here: https://github.com/RHEnVision/provisioning-frontend/blob/408b056951f8e60cc1829d1b13b05162e3593020/babel.config.js#L44
=> build: Disable relative import lint

.tekton/provisioning-frontend-push.yaml
The rpm-signature-scan was not present for frontend push pipeline and Enterprise contract failed on that.
=> build: Add rpm-signature-scan for push pipeline
