RHEnVision/provisioning-frontend

fec.config.js, src/API/helpers.js, src/Components/SourcesDropdown/index.js
=> Add dropdown for listing sources

package-lock.json, package.json, src/Components/Common/Query/index.js, src/Components/Wizard/index.js, src/Components/Wizard/steps/index.js, src/Routes/SamplePage/SamplePage.js
https://user-images.githubusercontent.com/11807069/177600142-bacea30f-78fe-400b-a952-d0a7ca709434.mov
=> Add wizard skeleton

src/Components/DescriptionListAWS/index.js, src/Components/ExpandableAWS/index.js, src/Components/Wizard/steps/ReviewDetails/index.js, src/Components/Wizard/steps/index.js
=> Add review details page

package.json
Set the app name properly in package.json.
=> Name the app

src/Components/Common/WizardContext/initialState.js, src/Components/DescriptionListAWS/index.js, src/Components/Wizard/index.js, src/Components/Wizard/steps/Pubkeys/NewKeyForm.js, src/Components/Wizard/steps/Pubkeys/index.js, src/Components/Wizard/steps/index.js
https://user-images.githubusercontent.com/11807069/185220431-e89670ee-5c73-45a8-970d-cd31a6ad0482.mov
=> HMSPROV-195 - UI for uploading new pubkey

src/Components/InstanceTypesSelect/index.js, src/mocks/fixtures/instanceTypes.fixtures.js
Depends on https://github.com/RHEnVision/provisioning-backend/pull/169
=> Add instance type info

src/API/index.js, src/mocks/handlers.js
Depends on https://github.com/RHEnVision/provisioning-backend/pull/139
=> Change instance_types endpoint

src/API/index.js, src/Components/InstanceTypesSelect/index.js
=> Add storage info

src/Routes/SamplePage/SamplePage.js
This adds an image select input in the provisioning demo page:
https://user-images.githubusercontent.com/11807069/187095532-a020470b-719d-49f8-911c-5906914e79f9.mov
=> HMSPROV-208 - Add image selector in demo page

src/API/index.js, src/API/queryKeys.js, src/Components/Common/WizardContext/initialState.js, src/Components/DescriptionListAWS/index.js, src/Components/ExpandableAWS/index.js, src/Components/Wizard/steps/Pubkeys/NewKeyForm.js, src/Components/Wizard/steps/Pubkeys/PubkeySelect.js, src/Components/Wizard/steps/Pubkeys/Pubkeys.test.js, src/Components/Wizard/steps/Pubkeys/index.js, src/Components/Wizard/steps/index.js, src/mocks/fixtures/pubkeys.fixtures.js, src/mocks/handlers.js
I've added the `uploadedKey` to the store and changed the validated step.
Error state:
=> Add public SSH key selection

src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js, src/Components/InstanceTypesSelect/index.js
I am tired of manually searching `t1.micro` all the time 🤣 
https://user-images.githubusercontent.com/11807069/187408684-e45baf67-ed41-4dfe-9d6d-ec6971451cb1.mov
=> Add instance types filter

package-lock.json, package.json
Reverts RHEnVision/provisioning-frontend#28
=> Revert "Bump react-router-dom from 5.2.0 to 6.3.0"

src/Components/Wizard/steps/Pubkeys/NewKeyForm.js
This allows editing of the key or inserting it manually.
=> Allow editing of the Uploaded pubkey

src/API/index.js, src/Components/Wizard/steps/FinishProgress/index.js
https://user-images.githubusercontent.com/11807069/190016430-3f1423bb-b7f6-4c6c-b0b7-9af8fcd67d0f.mov
=> HMSPROV-242 - add reservation polling

src/Components/Wizard/steps/FinishProgress/index.js
on top of #100 
This adds a back button if there is any error during deployment
https://user-images.githubusercontent.com/11807069/190150728-48484baa-6afd-4ded-bdd6-864857d895b0.mov
=> HMSPROV-282 - add back button in progress step when error occurred

src/Components/ProvisioningWizard/steps/Pubkeys/PubkeySelect.js, src/Components/SourcesSelect/index.js
=> Improve error states for async fetched data

src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js
https://user-images.githubusercontent.com/11807069/193471364-1483db08-b01d-428c-a700-8841b52c0f0d.mov
=> HMSPROV-290 - fix validations after clicking back

src/Components/ProvisioningWizard/index.js
=> Add image name to wizard description

src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js, src/Components/SourcesSelect/SourcesSelect.test.js, src/Components/SourcesSelect/index.js
Uses same components as other Selects, makes placeholder unselectable.
Fixes HMSPROV-293
=> Improve account select

src/Components/InstanceTypesSelect/index.js
Limit height to allow scroll on select items.
Add limit for items loaded at once to incentives usage of search.
Refs HMSPROV-292
[Screencast from 7.10.2022 13:01:30.webm](https://user-images.githubusercontent.com/2884324/194540628-f3e0d126-55b4-4d00-9cf1-1696a849e58e.webm)
=> Improve instance type select

src/Components/ProvisioningWizard/index.js, src/Components/ProvisioningWizard/steps/Pubkeys/NewKeyForm.js, src/Components/ProvisioningWizard/steps/Pubkeys/PubkeySelect.js, src/Components/ProvisioningWizard/steps/Pubkeys/Pubkeys.test.js, src/Components/ProvisioningWizard/steps/Pubkeys/index.js, src/Components/ProvisioningWizard/steps/Pubkeys/pubkeys.scss
* Disable clearing key from select
* Improve textation of SSH step
* Disable selecting key when there are no keys to select
[Screencast from 10.10.2022 10:02:35.webm](https://user-images.githubusercontent.com/2884324/194821955-e12e7b42-6d0d-465c-98dc-c4b5189979e6.webm)
=> Ssh step ux improvements

src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js, src/Components/InstanceTypesSelect/index.js
InstanceSelect had refreshed in cycles on no real input change.
Fixes HMSPROV-318
=> fix(InstanceSelect) stop refreshing component on no changes

fec.config.js, package.json
This exposes additional modules through fec config.
Depends on https://github.com/RedHatInsights/frontend-components/pull/1623
=> Expose Wizard through fec config

src/Components/ProvisioningWizard/steps/FinishProgress/index.js
Use correct icons, improve copywrites.
[Screencast from 11.10.2022 18:06:24.webm](https://user-images.githubusercontent.com/2884324/195152596-ba5bd573-2fd0-4d54-a9a1-97be241a3d23.webm)
=> UX(finish): Progress step UX

src/Components/ProvisioningWizard/steps/Pubkeys/NewKeyForm.js, src/Components/ProvisioningWizard/steps/Pubkeys/PubkeySelect.js, src/Components/ProvisioningWizard/steps/Pubkeys/index.js
Ready for review, I've checked the deployed image.
FileUpload doesn't actually support it, happy to remove that one if reviewers would rather it not be there until its supported.
=> Add ouia for pubkey

src/Components/InstanceCounter/index.js, src/Components/InstanceCounter/styles.css, src/Components/ProvisioningWizard/index.js
=> Align slider max label

src/Components/InstanceCounter/index.js, src/Components/InstanceCounter/styles.css, src/Components/ProvisioningWizard/index.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js, src/Components/ProvisioningWizard/steps/FinishProgress/index.js, src/Components/ProvisioningWizard/steps/Pubkeys/NewKeyForm.js, src/Components/ProvisioningWizard/steps/Pubkeys/index.js
=> UX enhancements

src/Components/ProvisioningWizard/steps/ReviewDetails/index.js
=> fix(text): Improve textation of review description

src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js, src/Components/InstanceTypesSelect/index.js, src/Components/ProvisioningWizard/index.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js, src/Components/ProvisioningWizard/steps/index.js, src/mocks/fixtures/instanceTypes.fixtures.js
Works with https://github.com/RedHatInsights/image-builder-frontend/pull/870
=> HMSPROV #355 - filter out unmatched architecture in instance types

src/Components/ProvisioningWizard/steps/index.js
Add default for arch for cases where it is not set on the image (like  the sample page)
=> Set default arch to x86_64

src/Components/ProvisioningWizard/steps/FinishProgress/index.js
In order to test the UI or connect to the progressing reservation for any other purposes, we need to expose the reservation id in the UI.
Fixes HMSPROV-359
=> feat(progress): add reservation id as hidden field

src/API/helpers.js, src/API/index.js, src/API/queryKeys.js, src/Components/Common/WizardContext/initialState.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js, src/Components/ProvisioningWizard/steps/FinishProgress/index.js, src/Components/ProvisioningWizard/steps/index.js, src/Components/RegionsSelect/RegionsSelect.test.js, src/Components/RegionsSelect/index.js, src/mocks/fixtures/image.fixtures.js, src/mocks/handlers.js
https://user-images.githubusercontent.com/11807069/204598061-23fce5aa-48d8-4c72-a3a9-ac30dd67b87d.mov
=> feat(HMSPROV-306) - add multi region select

src/API/index.js, src/Components/DescriptionListAWS/index.js, src/Components/SourcesSelect/index.js
This is a temporary fix until @amirfefer will finish adding the GCP and Azure UI part.
=> refactor: Add sources filtering by provider

.rhcicd/build_deploy.sh, .rhcicd/pr_check.sh, .rhcicd/sonarqube.sh
Uses the RH sonarqube for static code analysis.
=> build: Setup SonarQube analysis

src/Components/Common/helpers.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/index.js, src/Components/ProvisioningWizard/steps/ReservationProgress/helpers.js
It is considered a security risk.
=> chore: fix default statement issues

src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js, src/Components/InstanceTypesSelect/index.js, src/mocks/fixtures/instanceTypes.fixtures.js
=> fix(HMS-1237): show warning alert when instance type is not supported

.github/workflows/build-repo.yml, .github/workflows/provisioning-front.yml, .github/workflows/sync_branches.yml
I've mostly stolen https://github.com/RedHatInsights/image-builder-frontend/blob/main/.github/workflows/sync-branches.yml thanks @croissanne ! :)
=> build: Add sync branches workflow

src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js, src/Components/InstanceTypesSelect/index.js
Fixes HMS-1381
See `Selected` for the input and `Select` for the toggle, I'm not sure about that, share opinions pls :)
=> fix: instance type labels

.github/workflows/sync_branches.yml
=> build: Try real push

src/API/index.js, src/Components/Common/InstanceLink.js, src/Components/Common/constants.js, src/Components/Common/helpers.js, src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/azure.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/index.js, src/Components/ProvisioningWizard/steps/ReservationProgress/constants.js, src/Components/ProvisioningWizard/steps/ReservationProgress/helpers.js, src/Components/RegionsSelect/RegionsSelect.test.js, src/Components/RegionsSelect/index.js, src/constants.js, src/mocks/fixtures/instanceTypes.fixtures.js, src/mocks/handlers.js
Adds additional interval in the polling as it Azure can take a long time.
Fixes HMS-777
Needs Image Builder's PR as follow up (or for testing): https://github.com/RedHatInsights/image-builder-frontend/pull/1002
[Screencast from 2023-03-14 12-45-56.webm](https://user-images.githubusercontent.com/2884324/224994134-257975b2-875e-425b-8fa9-7137080b92d9.webm)
=> feat: Add Azure as provider in the wizard

src/Components/Common/Hooks/useInterval.js, src/Components/ProvisioningWizard/steps/ReservationProgress/ReservationProgress.test.js
Timeout error didn't appear correctly during launch progress, casued by a regression after switching to the progress steps. a test is added  for preventing such regression
=> fix(HMS-#1504): fix timeout interval regression during lanuch

config/jest.setup.js, package-lock.json, package.json, src/API/index.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js, src/Components/ProvisioningWizard/steps/ReservationProgress/index.js, src/Components/TemplateSelect/TemplateSelect.test.js, src/Components/TemplateSelect/index.js, src/mocks/fixtures/templates.fixtures.js, src/mocks/handlers.js
=> feat(HMS-1210): add launch template to wizard

src/Routes/SamplePage/SamplePage.js
=> test: enable Azure wizard from Sample page

src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/azure.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/gcp.js, src/Components/RegionsSelect/RegionsSelect.test.js, src/Components/RegionsSelect/index.js
Make the region select stateless.
This allows for use of the select on multiple places.
=> refactor: Stateless region select

src/Components/LaunchDescriptionList/index.js
=> fix(HMS-1573): add launch template name in review step

src/API/queryKeys.js, src/Components/LaunchDescriptionList/index.js, src/Components/TemplateSelect/TemplateSelect.test.js, src/Components/TemplateSelect/index.js
https://user-images.githubusercontent.com/11807069/235130165-0d58c2f4-66ca-4637-831e-f52dc046165a.mov
=> fix(HMS-1573): add clear button to template select

src/Components/ProvisioningWizard/steps/Pubkeys/NewKeyForm.js, src/Components/ProvisioningWizard/steps/Pubkeys/PubkeySelect.js, src/Components/ProvisioningWizard/steps/Pubkeys/Pubkeys.test.js, src/Components/ProvisioningWizard/steps/Pubkeys/helpers.js, src/Components/ProvisioningWizard/steps/Pubkeys/index.js, src/mocks/fixtures/pubkeys.fixtures.js
This PR adds a validation error when ed25519 public key foramt is picked up from existing keys select or when uploading a new key.
=> feat(HMS-1411):  ed25519 type is unsupported in azure

src/Components/InstanceCounter/constants.js, src/Components/InstanceCounter/index.js, src/Components/InstanceTypesSelect/InstanceTypesSelect.test.js
The most simple solution - but we can get the vCPU value into the context:) Depends if we'll need this.
=> feat(HMS-1614): Add vCPU limit Warning

README.md, config/routes.config.js, fec.config.js, package.json
is needed for https://github.com/RHEnVision/provisioning-backend/pull/539
=> feat(HMS-1907):  add dev script for containerizing provisioning env

src/Components/ProvisioningWizard/steps/AccountCustomizations/gcp.js
This PR introduces a launch template dropdown to the GCP menu. 
A big thank you to @amirfefer for implementing the dropdown in such a generic, clean, and clear manner!
=> feat(HMS-1978): Add launch templates to GCP

src/Components/ProvisioningWizard/steps/ReservationProgress/constants.js
Depended on https://github.com/RHEnVision/provisioning-backend/pull/593
=> feat(HMS-1955): Add fetch instance desc step for GCP

.rhcicd/pr_check.sh
Add deployment of Image builder to ephemeral during our PR checks
Add a stubbed Image into database directly.
For now this image is static, rebuilding it will be a followup PR.
=> ci: Include IB frontend and stub an image

src/Components/InstancesTable/index.js
https://github.com/RHEnVision/provisioning-frontend/assets/11807069/f1938055-c4f2-4e28-9618-274aaaf406f4
=> fix(HMS-2247): add spinner to instances table

.rhcicd/pr_check.sh
Older images have been removed
=> ci: Update image UUIDs

src/Components/InstanceCounter/InstanceCounter.test.js, src/Components/InstanceCounter/index.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/aws.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/azure.js, src/Components/ProvisioningWizard/steps/AccountCustomizations/gcp.js
=> feat(HMS-2341): refactor the instance counter alert to validation

.rhcicd/pr_check.sh
https://github.com/RHEnVision/provisioning-backend/pull/654
=> ci: Update image uuids frontend

src/Components/Common/Hooks/useLocalStorage.js, src/Components/ProvisioningWizard/steps/ReviewDetails/index.js
=> feat(HMS-2176): add info banner for notification

src/Components/SourcesSelect/index.js
=> fix(HMS-2350): Add a warning if source is unavailable

.rhcicd/pr_check.sh
=> ci: Image stub script from gitlab

src/API/helpers.js, src/API/index.js, src/Components/ProvisioningWizard/steps/Pubkeys/PubkeySelect.js, src/Components/ProvisioningWizard/steps/Pubkeys/Pubkeys.test.js, src/Components/ProvisioningWizard/steps/Pubkeys/index.js
[Screencast from 2023-09-20 14-33-03.webm](https://github.com/RHEnVision/provisioning-frontend/assets/57755873/5fef7d96-82f3-44d7-8150-49a4c03032b7)
=> feat(HMS-2227): Add Pubkeys pagination

deploy/testing-integration.yaml
Same as https://github.com/RHEnVision/provisioning-backend/blob/main/deploy/testing-integration.yaml
=> ci(HMS-3056): Adding integration testing template

.rhcicd/pr_check.sh
Same as https://github.com/RHEnVision/provisioning-backend/pull/765
=> ci: Change CICD_URL for pr_check

package-lock.json
Bumped packages: classnames, jsonata, react-tracked, ts-patch, typescript, undici, @testing-library/user-event
Fixes HMS-3769
=> build: Bump critical dependencies

README.md
App-interface MR 101254 is not self-serviceable and is taking time to get merged. Ideally that would trigger the pipeline as well.
I'd like to tigger the push before that.
=> ci: Trigger push to prod

deploy/testing-integration.yaml
Similar to https://github.com/RHEnVision/provisioning-backend/pull/781
=> ci: Disable parallel runs

deploy/testing-integration.yaml
Name update from hms-integration to insights-experiences.
=> ci(HMS-3962): Update Integration test image for IQE

.rhcicd/pr_check.sh
This will deploy the apps using whatever is in stage which is where PRs are deployed after being merged.
=> pr_check: use insights-stage as ref-env

package-lock.json
Bump braces and webpack-dev-middleware dependencies to latest versions.
Bump undici to latest version as well :)
=> build: Bump braces and webpack-dev-middleware

package-lock.json
=> build: Bump express from 4.18.2 to 4.19.2

package-lock.json, package.json
Mitigate the CVE in axios by the new release
=> build: Update axios

.github/workflows/provisioning-front.yml
Removes unused upload of artifact and bumps versions of GH actions.
=> ci(GHA): Update GH actions to latest versions
